import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./antd.min.css";
import "./globals.css";
import '@ant-design/v5-patch-for-react-19';
import AntdConfigProvider from "@/components/antd/AntdConfigProvider";
import {AntdRegistry} from "@ant-design/nextjs-registry";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <AntdRegistry>
            <AntdConfigProvider>
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased antd`}
                >
                {children}

                </body>
            </AntdConfigProvider>
        </AntdRegistry>
        </html>
    );
}
